version: '2'
services:
  nginx:
    build: nginx/
    ports:
     - "80:80"
    volumes:
     - ./nginx:/opt/flask
    depends_on:
     - web
  web:
    build: web/
    ports:
     - "8000:8000"
    volumes:
     - ./web:/opt/flask
